# Generated by Django 3.0.3 on 2020-02-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('source', models.CharField(default='凭空捏造', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.IntegerField(default=0, max_length=10, verbose_name='支持')),
                ('option2', models.IntegerField(default=0, max_length=10, verbose_name='反对')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='polls.Problem')),
            ],
        ),
    ]
