# Generated by Django 3.0.3 on 2020-02-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option3',
            field=models.CharField(choices=[('true', '支持'), ('false', '反对')], default='false', max_length=10, verbose_name='选项3'),
        ),
        migrations.AddField(
            model_name='option',
            name='option4',
            field=models.CharField(choices=[('true', '支持'), ('false', '反对')], default='false', max_length=10, verbose_name='选项4'),
        ),
        migrations.AddField(
            model_name='problem',
            name='option1_votes',
            field=models.IntegerField(blank=True, null=True, verbose_name='选项1票数'),
        ),
        migrations.AddField(
            model_name='problem',
            name='option2_votes',
            field=models.IntegerField(blank=True, null=True, verbose_name='选项2票数'),
        ),
        migrations.AddField(
            model_name='problem',
            name='option3_votes',
            field=models.IntegerField(blank=True, null=True, verbose_name='选项3票数'),
        ),
        migrations.AddField(
            model_name='problem',
            name='option4_votes',
            field=models.IntegerField(blank=True, null=True, verbose_name='选项4票数'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option1',
            field=models.CharField(choices=[('true', '支持'), ('false', '反对')], default='false', max_length=10, verbose_name='选项1'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option2',
            field=models.CharField(choices=[('true', '支持'), ('false', '反对')], default='false', max_length=10, verbose_name='选项2'),
        ),
    ]
