# Generated by Django 3.0.3 on 2020-02-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200215_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option1',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option2',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option3',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option4',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='option1_votes',
            field=models.IntegerField(default=0, verbose_name='选项1票数'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='option2_votes',
            field=models.IntegerField(default=0, verbose_name='选项2票数'),
        ),
    ]
