# Generated by Django 3.0.3 on 2020-02-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200215_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option1',
            field=models.CharField(default='支持', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option2',
            field=models.CharField(default='反对', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option3',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='option4',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
