# Generated by Django 3.0.3 on 2020-02-15 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200215_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='polls.Problem'),
        ),
    ]
