# Generated by Django 3.0.3 on 2020-02-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0008_auto_20200215_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='acticles',
            field=models.ManyToManyField(related_name='tags', to='booktest.Article'),
        ),
    ]
