# Generated by Django 3.0.3 on 2020-02-24 07:29

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='ads', verbose_name='图片')),
                ('desc', models.CharField(blank=True, max_length=20, null=True, verbose_name='图片说明')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教师姓名')),
                ('field', models.CharField(max_length=50, verbose_name='权威领域')),
                ('introduce', DjangoUeditor.models.UEditorField(verbose_name='简介')),
                ('stars', models.PositiveIntegerField(default=3, verbose_name='评价星级')),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教师姓名')),
                ('price', models.PositiveIntegerField(default=1000, verbose_name='课程费用')),
                ('days', models.PositiveIntegerField(default=7, verbose_name='课程时长')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='开课时间')),
                ('category', models.ManyToManyField(to='qikuapp.Category', verbose_name='授课分类')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qikuapp.Teacher', verbose_name='授课教师')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='评论人')),
                ('url', models.URLField(default='http://www.zzy.com', verbose_name='个人主页')),
                ('email', models.EmailField(default='1862655@qq.com', max_length=254, verbose_name='个人邮箱')),
                ('body', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qikuapp.Curriculum', verbose_name='所属课程')),
            ],
        ),
    ]
