# Generated by Django 3.0.3 on 2020-02-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikuapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=20, verbose_name='课程名'),
        ),
    ]
