# Generated by Django 3.0.3 on 2020-02-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qikuapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='user',
            name='curriculum',
            field=models.ManyToManyField(to='qikuapp.Curriculum'),
        ),
    ]
